USE [WorkWatch]
GO

/****** Object:  Table [AgTech].[Company]    Script Date: 08/02/2019 7:57:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [WorkWatch].[User](
	[UserID] [INT] IDENTITY(1,1) NOT NULL,
	[Username] [VARCHAR](256) NOT NULL,
	[MachineName] [VARCHAR](256) NOT NULL
 CONSTRAINT [PK_WorkWatch_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
